<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ZhuagepingRecorderHost</AssemblyName>
    <RootNamespace>ZhuagepingRecorderHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScreenRecorderLib" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
